add solution 1-9

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,10 +1,10 @@
 #!/bin/bash
-PYFILE = $PYFILE
+PYFILE=$PYFILE
 
 if [ -z "$PYFILE" ]; then
-echo "Error: PYFILE environment variable is not set"
-exit 1
+    echo "Error: PYFILE environment variable is not set"
+    exit 1
 elif [ -f "$PYFILE" ]; then
-echo "Error: $PYFILE does not exist or is not a file"
-exit 1
+    echo "Error: $PYFILE does not exist or is not a file"
+    exit 1
 fi
